# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:48:58+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class LatexCompiler(Enum):
    pdflatex = 'pdflatex'
    lualatex = 'lualatex'


class TemplatesTemplateTokenCompilePostRequest(BaseModel):
    pass


class TemplatesTemplateTokenCompilePostResponse(BaseModel):
    pass
